name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: string
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{github.repository}}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ steps.string.outputs.lowercase }}/bablobot:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ steps.string.outputs.lowercase }}/bablobot:latest